### ISSUE TITLE
Unrealizable policy?

### ISSUE THREAD

**Issue by mcanini** [frenetic-lang/frenetic#219]
Consider
```
filter switch = 1 and port = 1 and not (ethDst = 1); port := 2 |
filter switch = 1 and not (port = 1) and ethDst = 1; port := 1
```
currently katnetic produces a wrong flowtable:
```
[{pattern={port=1,action=,cookie=0,idle_timeout=Permanent,
 hard_timeout=Permanent}
{pattern={ethDst=1,action=OutputPort(1),cookie=0,idle_timeout=Permanent,
hard_timeout=Permanent}
{pattern={port=1,action=OutputPort(2),cookie=0,idle_timeout=Permanent,
hard_timeout=Permanent}]
```
Unfortunately, the input policy is in general unrealizable when targeting the OpenFlow model. You can either satisfy the left or the right side of the parallel composition.
If the compiler had information about the full set of ports on the switch, it could attempt to realize the policy correctly.

In principle, we could use a verification tool that takes the output of the compiler, turns it into a KAT policy and applies the equational theory to see if the output of the compiler is equivalent to the input, no?

**Comment by smolkaj** [comment]
outdated
