### ISSUE TITLE
OVS 1.3 in vagrant

### ISSUE THREAD

**Issue by reitblatt** [frenetic-lang/frenetic#228]
Need to update/test vagrant.

From Marco:

To install mininet
git clone git@github.com:mcanini/mininet.git
sudo mininet/util/install.sh -e
sudo mininet/util/install.sh -n

To install OpenVSwitch:

BUILD_DIR="$(pwd -P)"
KERNEL_NAME=`uname -r`
KERNEL_HEADERS=linux-headers-${KERNEL_NAME}
OVS_SRC=$BUILD_DIR/openvswitch
OVS_BUILD=$OVS_SRC/build-$KERNEL_NAME
OVS_KMODS=($OVS_BUILD/datapath/linux/{openvswitch_mod.ko,brcompat_mod.ko})

sudo apt-get -y install tmux zsh build-essential fakeroot $KERNEL_HEADERS libtool debhelper graphviz python-all python-qt4 python-zopeinterface python-twisted-conch
git clone git@github.com:mcanini/openvswitch.git $OVS_SRC
cd $OVS_SRC
DEB_BUILD_OPTIONS='parallel=64 nocheck' fakeroot debian/rules binary
cd ..
sudo dpkg -i openvswitch-common_*.deb openvswitch-switch_*.deb openvswitch-datapath-dkms_*.deb
sudo /etc/init.d/openvswitch-switch restart

**Comment by craig-riecke** [comment]
I'm gonna close this.  OpenVSwitch 2.1 is installed by the latest incarnation of frenetic/frenetic-vm (as part of Ubuntu 14.04 itself), and it's Openflow 1.3 compliant.  The gist referenced above is pretty much baked into the Vagrant setup.
