### ISSUE TITLE
Investigate better oasis camlp4 integration

### ISSUE THREAD

**Issue by reitblatt** [frenetic-lang/frenetic#230]
Right now we have to explicitly add `<foo/*.ml>: syntax_camlp4o` to our _tags file. There must be a way to get oasis to generate this for us.

**Comment by craig-riecke** [comment]
Since the parser realignment, we commented these two lines out.  Once I re-enable the NetKAT syntax extension, we may need to add it back ... but I don't think so.  It'll be a pretty standard syntax extension.

**Comment by craig-riecke** [comment]
FYI: I'm putting this on the front burner due to sudden academic interest.  The syntax extension actually seems to be OK now that we cleared the $ operators out of the main loop, so I'm compiling and testing it now.
