### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by reitblatt** [frenetic-lang/frenetic#233]
API documentation in http://frenetic-lang.github.io/frenetic/docs/index.html is super out-of-date

**Comment by craig-riecke** [comment]
Once I get #410 done, the API docs should become part of the CI process.  I think.

**Comment by craig-riecke** [comment]
Ready to tackle this again.  Travis CI scripts have an option to generate docs and push them back to Github (https://github.com/ocaml/ocaml-ci-scripts/blob/master/README-travis.md).

**Comment by craig-riecke** [comment]
All done as part of Pull Request #476
