### ISSUE TITLE
Hygiene

### ISSUE THREAD

**Issue by jnfoster** [frenetic-lang/frenetic#351]
Potentially controversial assertion: more important than whitespace or revision history is consistent directory structure, naming conventions, and especially interfaces.

Our file structure is currently a mess. We use a hodge-podge of naming conventions: in places we have NetKAT_X. In others we just have X. 

We lack .mli files for a number of .ml files.

IMO, this hygiene should be enforced, as soon as is practically feasible.

**Comment by craig-riecke** [comment]
I can't see anything in this issue that wasn't done in Frenetic 4.0 unified release.
