### ISSUE TITLE
frenetic: command not found

### ISSUE THREAD

**Issue by tianlewlh** [frenetic-lang/frenetic#378]
I installed frenetic.3.1.0 with opam on ubuntu, and run Repeater on Frenetic, but when i typed:
Frenetic Repeater.nc, it shows :
mininet@mininet-vm:~$ Frenetic Repeater.nc
frenetic: command not found 
how should I fix this problem?

**Comment by jnfoster** [comment]
The binary is `katnetic`.

**Comment by tianlewlh** [comment]
I try with katnetic.native Repeater.nc, but it still does not work

mininet@mininet-vm:~$ katnetic.native Repeater.nc
katnetic.native: command not found

**Comment by jnfoster** [comment]
Is the file in that directory? If so you probably need to type `./katnetic.native`.

**Comment by tianlewlh** [comment]
sorry, i can not find file katnetic.native in the system

mininet@mininet-vm:~$ sudo find / -name katnetic.native
mininet@mininet-vm:~$

**Comment by arjunguha** [comment]
Here is the issue: Frenetic on OPAM is just a library. It doesn't install the katnetic executable. I don't see why not. Let me quickly fix this.

**Comment by arjunguha** [comment]
Hi all. This has now been fixed. If you install Frenetic from OPAM it actually creates a binary called frenetic. The tutorial is out of date and we should really put some work into it.
