### ISSUE TITLE
Invalid flow table is being produced

### ISSUE THREAD

**Issue by jcollard** [frenetic-lang/frenetic#384]
The following produces a policy which drops all traffic:

```ocaml
open NetKAT.Std
open SDN_Types
open NetKAT_LocalCompiler
open Forwarding

let forwarding : policy =
  <:netkat<
   if ip4Dst = 10.0.0.1 then port := 1
   else drop
  >>

let firewall : policy =
  <:netkat<
    filter ethType = 0x800; (if ipProto = 0x01 then drop else $forwarding)
  >>
```

To get the generated network bdd and flowtable I added in:

```ocaml
let bdd = compile firewall
let ft = string_of_flowTable (to_table 0L bdd)

let main () = print_endline ft;
	      to_dotfile bdd "bdd.dot"

let _ = main ()
```

The generated dot file is here:
![broken](https://cloud.githubusercontent.com/assets/3529380/5883508/189fbec0-a321-11e4-80bb-1af0eae885e2.png)

And the pretty printed flow table output is:
```
[{pattern={nwProto=0x1},action=,cookie=0,idle_timeout=Permanent,hard_timeout=Permanent}
{pattern={ethTyp=0x800,ipDst=10.0.0.1},action=Output(1),cookie=0,idle_timeout=Permanent,hard_timeout=Permanent}
{pattern={},action=,cookie=0,idle_timeout=Permanent,hard_timeout=Permanent}]
```

The top pattern seems to be missing `ethTyp=0x800` and all traffic is being dropped.

If I change the compile line to the following:

```ocaml
let bdd = compile ~order:(`Static [EthType; Switch; Location; EthSrc; EthDst; Vlan; VlanPcp; IPProto; IP4Src; IP4Dst; TCPSrcPort; TCPDstPort]) firewall
```

The resulting flow table is:
```
[{pattern={ethTyp=0x800,nwProto=0x1},action=,cookie=0,idle_timeout=Permanent,hard_timeout=Permanent}
{pattern={ethTyp=0x800,ipDst=10.0.0.1},action=Output(1),cookie=0,idle_timeout=Permanent,hard_timeout=Permanent}
{pattern={},action=,cookie=0,idle_timeout=Permanent,hard_timeout=Permanent}]
```

And dot file is: 
![better](https://cloud.githubusercontent.com/assets/3529380/5883573/b3409bb6-a321-11e4-8980-ae6fc8babee1.png)

This results in the desired behavior. It seems that the compiler is using an order that results in an invalid flow table.

**Comment by arjunguha** [comment]
Er--does this patch address the issue? https://github.com/frenetic-lang/frenetic/pull/375

**Comment by arjunguha** [comment]
This is fixed.
