### ISSUE TITLE
app.App not receiving all EVENT's

### ISSUE THREAD

**Issue by nbraga** [frenetic-lang/frenetic#395]
After building the latest `shell` branch several days ago, I have noticed that App's (Parent class: lang/python/frenetic/app.py) consistently receive (and print to console -- ln. 81 app.py) the following (incorrect) EVENT's only, regardless of mn topology:
On launch of mn:
`EVENT: {u'type': u'switch_up', u'switch_id': 1}
EVENT: {u'port_id': 1, u'type': u'port_down', u'switch_id': 1}`
On close of mn:
`EVENT: {u'type': u'switch_down', u'switch_id': 1}`

**Comment by arjunguha** [comment]
How was it fixed?
