### ISSUE TITLE
Documentation for Frenetic

### ISSUE THREAD

**Issue by roney-michael** [frenetic-lang/frenetic#404]
Hi is there any formal documentation available for Frenetic?

Additionally, I'm trying to get through the [tutorial](https://github.com/frenetic-lang/frenetic/wiki/Frenetic-Tutorial), but we keep running into the issue mentioned [here](https://github.com/frenetic-lang/frenetic/issues/104) and are not able to proceed. The resolution for that issue seems incomplete as far as I understood it. Is the VM not directly usable out of the box?

**Comment by jnfoster** [comment]
Hi Roney,

1) Have you tried the `ox-build` command? It wraps some other OCaml build tools with the appropriate arguments.
https://github.com/frenetic-lang/tutorials/blob/master/scripts/ox-build
I see that the tutorial text still mentions using `make`. This needs to be updated, thanks.
2) The main documentation for `ox`, `ocaml-openflow`, `frenetic`, etc. at the moment are `.mli` files, which specify the main interfaces and include literate code comments and the tutorials themselves. Making a proper hackers manual is also on our TODO list.

-N

**Comment by jnfoster** [comment]
Roney, 

Did `ox-build` work for you?

-N

**Comment by roney-michael** [comment]
Hi Nate,
Sorry for the late reply, but the VM does not seem to have ox installed from what I was able to gather. Is this accurate?

> vagrant@frenetic:~/src/frenetic/ox-tutorial-workspace$ ./ox-build Repeater.d.byte
> ocamlfind ocamldep -package ox -package async -package core -modules Repeater.ml > Repeater.ml.depends
> + ocamlfind ocamldep -package ox -package async -package core -modules Repeater.ml > Repeater.ml.depends
> ocamlfind: Package `ox' not found
> Command exited with code 2.

**Comment by jnfoster** [comment]
The solution to this issue is simple

````
opam install ox
````

But I'm starting to wonder: which VM do you have? Did you get it from the
link here? (http://frenetic-lang.github.io/tutorials/Introduction/)

**Comment by roney-michael** [comment]
I'd run into some errors on trying `opam install ox` as well.

I seem to be following another version of the tutorial ([here](https://github.com/frenetic-lang/frenetic/wiki/Frenetic-Tutorial)) with the VM listed there ([here](https://github.com/frenetic-lang/frenetic/releases/frenetic-1.0.1)), which seems to be different. I'll try it out with this new one. Thanks!

**Comment by jnfoster** [comment]
Oh drat. Yes, that is what I was afraid of. That code is really old.

@arjunguha let's delete the ancient Wiki.

-N
