### ISSUE TITLE
http-controller Starts up Two Listeners to Port 6633

### ISSUE THREAD

**Issue by craig-riecke** [frenetic-lang/frenetic#408]
Nate, I think you might have introduced a bug in the Unified branch commit ff4bc1a8, specifically in frenetic/Http_Controller.ml.  When the controller is started with an alternate openflow port, everything appears fine:

```bash
vagrant@frenetic:~/src/frenetic$ ./frenetic.native http-controller --openflow-port=6634
```

But starting it with defaults gives the following:

```bash
agrant@frenetic:~/src/frenetic$ ./frenetic.native http-controller
((pid 2933) (thread_id 0)
 ((human_readable 2015-05-14T15:25:40+0000)
  (int63_ns_since_epoch 1431631540973815000))
 "unhandled exception in Async scheduler"
 ("unhandled exception"
  ((lib/monitor.ml.Error_
    ((exn
      (Unix.Unix_error "Address already in use" bind
       "((fd 7) (addr (ADDR_INET 0.0.0.0 6633)))"))
     (backtrace
      ("Raised at file \"lib/fd.ml\", line 225, characters 24-27"
       "Called from file \"lib/deferred.ml\", line 15, characters 64-67"
       "Called from file \"lib/job_queue.ml\", line 164, characters 6-47" ""))
     (monitor
      (((name Tcp.close_sock_on_error) (here ()) (id 5) (has_seen_error true)
        (is_detached true) (kill_index 0))))))
   (Pid 2933))))
```

It appears that http_controller calls Frenetic_OpenFlow0x01_Controller.init at the beginning, which I believe starts to listen on the command-line-provided OpenFlow port (6634 in the first example), and later calls Controller.start, which starts a listener on port 6633, ignoring the command-line-provided port.  That's why the first command works and the second doesn't.

I thought at first it might have been caused by my latest commit, but I checked out HEAD-1 and it did the same thing.

**Comment by jnfoster** [comment]
Yes, I agree. My mistake. I should have mentioned: as I've been merging /
porting, I've been making sure the code compiles but haven't been running
or testing. So I expect there will be more small issues like this.

"Friends don't let prof friends write code?" ;-)

-N

**Comment by jnfoster** [comment]
Happy to be assigned. Shall I push to unified? Or wait until you merge and then address?

**Comment by craig-riecke** [comment]
If you could push to Unified that'd be cool.  I wanna make sure each of my refactorings keep the server running ... at least superficially.

Oh, and don't sweat the prof-level code.  You have approval authority over my vacations, so I think you're doing great!  :-)

**Comment by craig-riecke** [comment]
Commenting out the extra init did the trick.  I am closing this since it was only an issue in the Unified branch.
