### ISSUE TITLE
TravisCI Build Not Succeeding - OPAM Package Error

### ISSUE THREAD

**Issue by craig-riecke** [frenetic-lang/frenetic#410]
This seems to have been happening for a few months.  Tried some trivial workarounds, none of which worked.  A similar clean build works fine on the Frenetic VM, so it's unlikely there's a real checksum error.  Both TravisCI and the clean build pull the package description from the same default OPAM repository, and the package itself from the same URL.  It sounds like TravisCI might be getting some cached, incorrect version of quickcheck-1.0.2.zip.  

```
[ERROR] Bad checksum for
        /home/travis/.opam/packages.dev/quickcheck.1.0.2/1.0.2.zip:
          - bb8b8180995030c8880cc2aaf9002964 [expected result]
          - 286b23c81a22bbca060e4e39d0a6c12c [actual result]
        This may be fixed by running `opam update`.
```

Oh, and "opam update" is unlikely to fix anything since OPAM is initialized from scratch on every TravisCI build.

**Comment by arjunguha** [comment]
yeah,I tried a few times too. No luck. No idea what's wrong.
