### ISSUE TITLE
type bytes in Frenetic_Packet.mli causes confusion

### ISSUE THREAD

**Issue by arjunguha** [frenetic-lang/frenetic#431]
OCaml 4.02 introduced a new type called bytes. Core.Std exposes it too:

 https://ocaml.org/releases/4.02.html

**Comment by craig-riecke** [comment]
Is this still causing compilation problems?  If so, there's a fix in Issue #425.

**Comment by arjunguha** [comment]
That's part of the fix. I think we shouldn't create our own type called `bytes` either. Perhaps we could rename our `type bytes =` to `type cstruct`?

**Comment by craig-riecke** [comment]
Oh yeah ... that is definitely confusing.  I can take care of this if you don't mind.

**Comment by craig-riecke** [comment]
Blurrgh.  Turns out you can't use 

```
type cstruct = ...
```

Because the camlp4 syntax extension for CStruct sees cstruct as a reserved word and tries to expand it.  You got around that for your changes in ppx_pretty branch because you turned off camlp4 for files there.

I could change it to "cstruct_bytes".  That's slightly less confusing than "bytes", but more verbose.

**Comment by arjunguha** [comment]
Why not cbtyes?

:)

**Comment by craig-riecke** [comment]
cbytes works for me!

**Comment by arjunguha** [comment]
not serious!!

**Comment by craig-riecke** [comment]
:-)  All righty.   We could also just forgo using a type alias and use Cstruct.t everywhere.  Or just leave it as bytes for now and wait for Cstruct to get converted to ppx.  That sounds imminent anyway...

**Comment by craig-riecke** [comment]
I'd like to get this issue resolved.  Turns out leaving it as bytes is causing pain. Pinning Core to 111.24 has caused fresh installs to sputter and require manual intervention.  

My pref would be to forgo the type alias and just use Cstruct.t.  But a better type alias name would be fine as well.

**Comment by arjunguha** [comment]
yeah agreed

**Comment by craig-riecke** [comment]
Fixed in pull request #439.
