### ISSUE TITLE
MapReduce example breaks global compiler

### ISSUE THREAD

**Issue by mcanini** [frenetic-lang/frenetic#432]
@jnfoster, @smolkaj

On the virtual branch:
```
cd examples/virtual/tswitch
./run-mapreduce.sh
```

Based on the derived global policy, the compiler will produce this error:
```
compile-server: internal error, uncaught exception:
                (lib/core_hashtbl.ml.Add_key_already_present 264)
                Raised at file "lib/core_hashtbl.ml", line 163, characters 11-40
```

**Comment by jnfoster** [comment]
````
% ./run-mapreduce.sh 
g_fabric
Error: dot: can't open g_fabric.dot
g_pruned
Error: dot: can't open g_pruned.dot
pg
Error: dot: can't open pg.dot
vg
Error: dot: can't open vg.dot
g_raw
Error: dot: can't open g_raw.dot
````

**Comment by mcanini** [comment]
@jnfoster you don't see a compiler error?

You can ignore the error raised by dot. The fact that you have those errors though means that the executable terminated before it reaches the point in which it outputs to file.

**Comment by smolkaj** [comment]
This was fixed with https://github.com/frenetic-lang/frenetic/commit/88f0e7e53f44400f6874be067cc16898b0a62175.
