### ISSUE TITLE
NetKAT Pragmas or Decorations

### ISSUE THREAD

**Issue by craig-riecke** [frenetic-lang/frenetic#434]
Increasingly, we're developing options that control the output of Frenetic, but are not really part of the NetKAT program.  Examples are:

* Field Ordering - Heuristic, Default, Fixed
* OpenFlow Version - 1.0 or 1.3

And I can think of a bunch of others on the horizon, like:

* Switch Type - Dell, HP 
* Table Configuration (which looks like it's implemented in the OpenFlow 1.3 branch)

It seems like these are the equivalent to Pragmas in older programming languages - they basically say "this isn't the program, but it changes the output of the compiler".  

I'm proposing a standard, scalable mechanism for these.  In the http-controller and compile-server versions of Frenetic, they can be passed as query parameters to /update and /update_json.  In the shell, they can be commands "set ___ =  ____".  Alternatively they could be embedded in NetKAT with a syntax like "@field_ordering Heuristic" although decoupling them from NetKAT is better IMHO.  

In the background, they'd be a plain ol' record type, attached to a DynGraph node along with the NetKAT policy.

**Comment by arjunguha** [comment]
Thoughts:

- Headers in HTTP requests. So RESTfu. Good idea.
- Attach to DynGraph nodes: some of these options have to be global and cannot vary from app to app. Actually, all the ones you list are global settings.

**Comment by jnfoster** [comment]
This is a great idea. In fact, having a compiler that specialized its backed end based on "switch manifests" was something included in the original grant proposal on Frenetic (submitted ca. 2010). I think @jrexford came up with that :-)

-N

**Comment by craig-riecke** [comment]
@arjunguha Yeah, you're right ... I forgot that the flow-tables are synthesized after the entire DynGraph is traversed.  Given that, I can't think of any app-specific configuration parameters.  The parameters I have listed above would be controller-wide state.  

There are two ways I can think of to implement a controller-wide config:

* A config file in /etc/frenetic.conf
* A REST verb POST /config.  Although two apps could walk all over each other's configs, I like the idea of having all the config app in the app

These are not mutually exclusive, and they might as well use the same JSON format.  So I could do both.  

Although I don't have an immediate need for switch-specific configs, they'd be easy to implement with this mechanism - a JSON hash with datapath id's as keys.  

Sound good?  I'm pushing this because I need to be able to control field order to make the Dell learning switch app work.

**Comment by arjunguha** [comment]
IMO

![49772823](https://cloud.githubusercontent.com/assets/20065/9384254/4669bfae-471d-11e5-9ee1-95255455b3d3.jpg)

**Comment by craig-riecke** [comment]
A very small REST+JSON global configuration language was introduced in Pull Request #416.
