### ISSUE TITLE
Unit Tests for Openflow 1.3

### ISSUE THREAD

**Issue by craig-riecke** [frenetic-lang/frenetic#438]
I did some quick lines of code metrics and found lib/Frenetic_OpenFlow* represents about 55% of the Frenetic code base.  These modules parse and construct OpenFlow messages. Only a small portion of Frenetic_OpenFlow0x01 is covered by unit tests, and those tests are of dubious value - they merely construct an abstract Openflow message, turn it into bits, turn those bits back into an abstract Openflow message and compare.  If you get, say, the message type wrong, you'd never uncover the bug this way.

To construct good unit tests, I'd write a RYU program which constructs bits and abstract messages, and spits out an Ocaml test to compare them.  Although that sounds like an awful lot of trust in RYU, the only false negatives will show up if RYU and Frenetic make the same mistake - pretty unlikely.  

If this works well, I might write unit tests for Frenetic_Openflow0x01, but only if we plan to keep it.  

@arjunguha I'd like to put this on the openflow13 branch if you don't mind.

**Comment by arjunguha** [comment]
I believe the openflow13 branch has been merged-in. We should probably delete it and create a new openflow13 branch for this. @jcollard can confirm

**Comment by jcollard** [comment]
That is correct. I've gone ahead and killed the old one and created a new one.

**Comment by craig-riecke** [comment]
All righty, I added unit tests for marshaling/parsing every Openflow 1.3 message to the openflow13 branch.   That alone extends test coverage 44%, so we're hovering at about 50% coverage for all of Frenetic.  

I also added a Python script which exercises RYU to actually write the test data.  So writing unit tests for Openflow 1.4, etc. will be much easier - just add the new cases to the script, generate the data, write the amended tests, and yr done.  

Frenetic_OpenFlow0x04 is incredibly clean!  I found and fixed only a few dinky bugs, mostly in code that hasn't been exercised in Frenetic yet.  Kudos to @jcollard, @mcanini, @mulias and everyone else who had a part in it.

**Comment by arjunguha** [comment]
Wow! Tests!

The credit really goes to Marco, Spiros, and Mark, and Thien. But, it was mostly Thien Duc Nguyen, who wrote hammered out the first version of the bindings last summer. Joe and Elias fixed a few bugs this summer, but the OpenFlow 1.3 bindings are largely Thien's work.

Arjun

**Comment by jnfoster** [comment]
+1 Tien is awesome!!

**Comment by mcanini** [comment]
+1!

**Comment by fugitifduck** [comment]
Thanks, if need more unit test or implementation on of1.5, ping me!
