### ISSUE TITLE
Removing old branches (global-compiler, global-compiler-with-sound-links, virtual-compiler3)

### ISSUE THREAD

**Issue by smolkaj** [frenetic-lang/frenetic#442]
Is anyone still using the branches `global-compiler`, `global-compiler-with-sound-link`, or `virtual-compiler3`? If not I will delete them. @basus

**Comment by basus** [comment]
I'm not using any of them. The only ones I'm using are `optical` and `fujitsu`.

**Comment by smolkaj** [comment]
Ok cool.

**Comment by craig-riecke** [comment]
I'm not aware of anyone using them.

**Comment by smolkaj** [comment]
Ok, 3 less branches to worry about.
