### ISSUE TITLE
website outdated

### ISSUE THREAD

**Issue by smolkaj** [frenetic-lang/frenetic#446]
We should at least update the list of publications.

**Comment by jnfoster** [comment]
Excellent point. Would you like to be the new webmaster? It could use a refresh and another person keeping on top of it.

**Comment by smolkaj** [comment]
Yes, I can take care of it.

**Comment by basus** [comment]
I have some experience using Bootstrap and find it really useful. Let me know if you want help.

**Comment by smolkaj** [comment]
Ok, will do. Thanks!

**Comment by smolkaj** [comment]
The website has been updated.
