### ISSUE TITLE
NetKAT JSON IP4 Inconsistency

### ISSUE THREAD

**Issue by mwhittaker** [frenetic-lang/frenetic#450]
There are some inconsistencies between the parsing and serialization of IPv4 headers to and from JSON. More specifically, `Frenetic_NetKAT_Json.ml` [serializes `IP4Src` and `IP4Dst` header values into JSON objects][ip_to_string], but it [parses IP source and destination addresses expecting they're just strings][ip_from_string]. There are some other discrepancies too (e.g. [`"ip4dst"`][ip4dst] vs [`"ipDst"`][ipdst]). 

I can write up a fix.

[ip_from_string]: https://github.com/frenetic-lang/frenetic/blob/8c64e57d78e73f168ea6c8d780bd3c339e59d62b/lib/Frenetic_NetKAT_Json.ml#L148-L149
[ip_to_string]: https://github.com/frenetic-lang/frenetic/blob/8c64e57d78e73f168ea6c8d780bd3c339e59d62b/lib/Frenetic_NetKAT_Json.ml#L51-L57
[ip4dst]: https://github.com/frenetic-lang/frenetic/blob/8c64e57d78e73f168ea6c8d780bd3c339e59d62b/lib/Frenetic_NetKAT_Json.ml#L72
[ipdst]: https://github.com/frenetic-lang/frenetic/blob/8c64e57d78e73f168ea6c8d780bd3c339e59d62b/lib/Frenetic_NetKAT_Json.ml#L149

**Comment by jnfoster** [comment]
Oh man :-( Thanks for fixing this.

**Comment by arjunguha** [comment]
Oh wow.

**Comment by seliopou** [comment]
```ocaml
type ip_addr = Ipaddr.V4.Prefix.t

let ip_addr_to_yojson ip =
  `String (Ipaddr.V4.Prefix.to_string ip)

let ip_addr_of_yojson = function
  | `String str ->
    begin match Ipaddr.V4.Prefix.of_string str with
    | None -> `Error (Printf.sprintf "unable to parse: %S" str)
    | Some ip -> `Ok ip
    end
  | _ -> `Error "expecting string but got someting else"
```

Also see whitequark/ppx_deriving_yojson#37. Haven't gotten around to it yet.

**Comment by craig-riecke** [comment]
Ok fixed is merged in.  Thanks for pointing this out @mwhittaker and for fixing it @smolkaj.

**Comment by mwhittaker** [comment]
Oops, I had forgotten about this :P. Thanks for the fix @smolkaj!
