### ISSUE TITLE
Extensions for Python Bindings

### ISSUE THREAD

**Issue by craig-riecke** [frenetic-lang/frenetic#465]
After writing a few net apps in Python using Frenetic, and starting to write a manual for the Python bindings as well, I've learned a few things:

1)  There are too many parantheses
2)  There is too much explicit switching between Policy-land and Predicate-land

Fortunately, there are some easy-to-implement, backwards-compatible syntax extensions that could streamline app writing.

Current Syntax | New, Alternative Syntax 
---------- | ---------------
Test(Switch(2)) | SwitchEq(2) :boom: 
Not(Test(Switch(2))) | SwitchNotEq(2) 
Test(EthType(0x800)) \| Test(EthType(0x806)) | EthTypeEq([0x800, 0x806])
Test(Ip4Src("128.96.56.0","24") | Ip4SrcEq("128.96.56.0/24")
Test(Location(Physical(5))) | PortEq(5)
Mod(Location(Physical(9))) | Output(9) :musical_note: 
Mod(Location(Pipe("myapp"))) | SendToController("myapp")
Mod(Ip4Dst("128.65.12.34")) | SetIp4Dst("128.65.12.34")
Filter(Test(Switch(2)) & Test(Port(5))) >> Mod(Location(Physical(9))) | SwitchEq(2) & PortEq(5) >> Output(9) :8ball: 

:boom: We might be able to do Switch == 2 since operators can be redefined.  But it's not clear this would work well.  
:musical_note:  The Output syntax is currently reserved for Packet Out operations, but here it would be extended for predicates as well.  
:8ball: Here, the >> would automatically convert a predicate on its LHS to a Filter Policy.

**Comment by craig-riecke** [comment]
@arjunguha @jnfoster and anyone else ... comments are welcome!

**Comment by arjunguha** [comment]
Music? Eight ball? What?

**Comment by jnfoster** [comment]
You have to admit: the eightball is definitely an improvement on the old
syntax.

**Comment by arjunguha** [comment]
Don't we need python 3 for unicode support?

**Comment by jnfoster** [comment]
But the Batman-esque "Pow!" for switch tests takes the cake.

**Comment by arjunguha** [comment]
oh wait... this is actually intended. i get it now. back to serious mode.

**Comment by arjunguha** [comment]
This is good: `EthTypeEq([0x800, 0x806])`. Why not make all atoms var-arity.

E.g., `SwichEq([1,2,3])`.

**Comment by smolkaj** [comment]
I think users will be surprised to find out that `PortEq(x)` and `Output(y)` don't commute...
Maybe we can make it so they do commute?

**Comment by craig-riecke** [comment]
@arjunguha: Yeah, my plan was to make orthogonal extensions for all NetKAT fields - all would have a "__Eq", "__Neq", "Set___" and all would tests would accept lists.  

Of course, if we're going to extend NetKAT itself with emoji's, then an open research topic must be to define the "poop" operator (emoji not shown here for decorum).  I leave that in your capable hands.  :-)

**Comment by craig-riecke** [comment]
@smolkaj You mean commute under >> (the NetKAT sequence operator, in Python-land)?  I don't think they oughta.  They do commute under | (the NetKAT union operator), but no one would use them that way.  

Nevertheless, making Output act like a policy AND an action was problematic.  So I'm proposing Send(n) as the action equivalent to Mod(Location(Physical(n)).  

I have decided to make varargs equivalent to sending a list in all policies and Send().  So:

SwitchEq(2, 3) = SwitchEq([2,3]) = Or(Test(Switch(2)), Test(Switch(3)))

I'm not sure how often people would use varargs, but it's an easy and sensible extension.

**Comment by smolkaj** [comment]
@craig-riecke: Yes, i meant under >>. Given that you call tests of the port field `PortEq` and modifications of the port field `Output` (or `Send`), I think it will come as a surprise to new users that the two commands are intimately connected. It makes sense in NetKAT, because there it is a test and modification of the __same field__. But with the new names, your obfuscating that connection. I suspect that users would expect `PortEq` to test the input port, and `Output` (or `Send`) to set the output port; but given that interpretation, the two should commute.

**Comment by craig-riecke** [comment]
@smolkaj, OK that makes sense now.  Send or Output sound too destructive, so you'd expect:

Send(9) >> SetIp4Src("127.0.0.1") >> drop

To send an unmodified packet to port 9.  In fact, this policy's flow table simply drops the packet.  Something like:

SetPort(9) >> SetIp4Src("127.0.0.1") >> drop

Makes it clearer what's going on.  I'd be fine with calling it SetPort.

**Comment by smolkaj** [comment]
Yes, I think that's clearer.
