### ISSUE TITLE
Upgrade Core, Fieldslib, Sexplib to 113.0, Using New PPX-Based Extensions

### ISSUE THREAD

**Issue by craig-riecke** [frenetic-lang/frenetic#479]
Remove pin on core at 112.35 introduced in #463.  This may or may not work because (1) other libraries we use - cstruct in particular - still use camlp4 (2) camlp4 is actually used for the file-based NetKAT parser (3) and obviously camlp4 is also used for the NetKAT syntax extension.  If PPX and camlp4 can't coexist, we may have to just upgrade it all at once.

**Comment by craig-riecke** [comment]
@smolkaj Do you have cycles to devote to this?  Nate hinted you might be interested.  If so, please grab it!

**Comment by seliopou** [comment]
This may come in handy for the ppx port:

  http://rgrinberg.com/blog/2016/02/15/scrap-your-camlp4/

**Comment by craig-riecke** [comment]
From the post that @seliopou referenced (thanks for that BTW):

1) Only the very latest version of the compiler (4.02.3) works with the most common ppx’s.

That makes me queasy - we're forcing a compiler version onto anyone compiling Frenetic.  It's not much better than locking down all the versions of Core, Fieldslib, etc. to their 112.x versions.  If anyone has an opinion on that, or alternatives, I'm all ears.

Meanwhile, since this is blocking my pull requests, I'm going to grab this and at least try to make PPX work on a branch with a fresh copy of frenetic-vm.

**Comment by jnfoster** [comment]
Until we have a large user base, I'm not worried about backward
compatibility. Insisting on recent versions of OCaml (all available in
OPAM) seems fine to me.

-N

**Comment by smolkaj** [comment]
I agree. As far as I know, switching between different versions of OCaml is trivial with opam.

**Comment by craig-riecke** [comment]
The scripts don't work - camlp4 (which they use to actually rewrite the source files, ironically) blows up on every file, zeroing out every one.  But it turns out the conversions handled by camlp4-to-ppx are trivial anyway.  The tough stuff was the cstruct/cenum, which is pervasive through the Frenetic_OpenFlow0xxx, and which has no converter.  Got those done.

However the result (on the issue_479_ppx branch) does not compile because of functor craziness.  The following:

```
    module VL = struct
      type t =
          { id : int;
            label : Vertex.t } [@@deriving sexp]
      let compare n1 n2 = Pervasives.compare n1.id n2.id
      let hash n1 = Hashtbl.hash n1.id
      let equal n1 n2 = n1.id = n2.id
      let to_string n = string_of_int n.id
    end


    module VertexSet = Set.Make(VL) (* line 177 *)
``` 

Generates error:

```
vagrant@frenetic:~/src/frenetic$ make
ocaml setup.ml -build -j 4
Finished, 0 targets (0 cached) in 00:00:00.
+ /home/vagrant/.opam/system/bin/ocamlfind ocamlc -c -w -40 -short-paths -g -annot -bin-annot -thread -thread -package yojson -package ulex -package threads -package tcpip -package str -package sexplib -package ocamlgraph -package fieldslib -package cstruct -package core -package base64 -I lib -o lib/Frenetic_Network.cmo lib/Frenetic_Network.ml
File "lib/Frenetic_Network.ml", line 177, characters 32-34:
Error: Signature mismatch:
       ...
       The value `sexp_of_t' is required but not provided
       The value `t_of_sexp' is required but not provided
Command exited with code 2.
```

Which makes no sense since the `[@@deriving sexp]` is supposed to do what `with sexp` did and add these functions.  Ugggh.

**Comment by smolkaj** [comment]
You may have forgotten to compile this with ppx_deriving enabled. (Since `[@@deriving sexp]` is just an AST annotation, it will compile even if ppx_deriving is not enabled.)

**Comment by craig-riecke** [comment]
@smolkaj It was far from clear that's what was happening, but you were correct.  To make the compilation work, you have to include ppx_sexp_conv, which sets the proper flags.  I had tried that earlier, but it was generating a ton of warnings.  I just learned to live with them.  

Everything's now compiling and running EXCEPT the tests.  The Lexer and Parser still need the camlp4 pre-processor run on them, but it then gets out of the way.  The NetKAT camlp4 syntax extension also compiles and runs fine.   I'd like to open a new issue to convert those since they're not really in the way.

The tests used to rely on a camlp4 extension from Jane Street.  They have a PPX, which I've switched over to using, but they don't seem to work with Oasis.   Logging an issue.
