### ISSUE TITLE
Do Queries Actually Work?

### ISSUE THREAD

**Issue by craig-riecke** [frenetic-lang/frenetic#492]
It was said in Issue #35 that NetKAT queries work, but:

```
drop |
filter ethTyp = 0x800 and ipProto = 0x6 and tcpSrcPort = 80;
port := query(http)
[DEBUG] Setting up flow table
+-------------------------------+
| 1 | Pattern          | Action |
|-------------------------------|
| TCPSrcPort = 80      |        |
| ipProto = 0x6 (tcp)  |        |
| EthType = 0x800 (ip) |        |
|-------------------------------|
|                      |        |
+-------------------------------+
```

The query is installed to some extent because if I send /query/http it gives me back 0,0 as the answer and if I send /query/crapola, it gives me "crapola is not defined in the current policy".  But it never gives me anything other than 0,0

**Comment by jnfoster** [comment]
Hmm. That's definitely a bug.

-N

**Comment by craig-riecke** [comment]
I can take this, but how is it **supposed** to work?  It seems like it should be turned into an OpenFlow SendToController, which sends the packet to Frenetic, tallies it in the bucket and drops it (as opposed to making a Packet In event out of it).

**Comment by jnfoster** [comment]
If it's a packet query, then yes it should be generating a ToController
action.

If it's a statistics query, then not having any action is fine -- the
controller can probe to get the counters.

Let's discuss in person next week.

-N

**Comment by craig-riecke** [comment]
There was a bug in my NetKAT and flow table.  It should have been TCPDstPort=80, not TCPSrcPort=80.  So queries basically map to one or more flow entry patterns, then Frenetic asks for all the stats on flow entries that match these patterns.  Fair 'nuff.  It works if your only action is the Query, so the NetKAT (here in Python dialect):

```
IfThenElse(
   EthTypeEq(0x800) & IPProtoEq(6) & TCPDstPortEq(80),
   Mod(Location(Query("http"))), 
   SetPort(1) | SetPort(2)
)
```

Yields the right query stats for "http".  But when you add this:

```
IfThenElse(
   EthTypeEq(0x800) & IPProtoEq(6) & TCPDstPortEq(80),
   Mod(Location(Query("http"))) >> SetPort(2), 
   SetPort(1) | SetPort(2)
)
```

Although OpenVSwitch is counting the packets properly:

```
mininet> sh ovs-ofctl dump-flows s1
NXST_FLOW reply (xid=0x4):
 cookie=0x0, duration=15.164s, table=0, n_packets=5, n_bytes=222, idle_age=1, priority=65534 actions=output:2,output:1
 cookie=0x0, duration=15.164s, table=0, n_packets=1, n_bytes=74, idle_age=6, priority=65535,tcp,tp_dst=80 actions=output:2
```

The query is coming back with zeroes.  So it seems Frenetic is no longer grabbing the right individual flow stats.

**Comment by craig-riecke** [comment]
Never mind.  If you turn it into a Union, it works.  The semantics are a little weird (counting packets should not change the packet in any way, after all), but they're consistent with how other types of Mod(Location) works.  I'll document that in the manual.  

```
IfThenElse(
   EthTypeEq(0x800) & IPProtoEq(6) & TCPDstPortEq(80),
   Mod(Location(Query("http"))) | SetPort(2), 
   SetPort(1) | SetPort(2)
)
```

**Comment by smolkaj** [comment]
Craig, note that ports, queries, and pipes are all modeled as locations. If you modify the location twice in sequence, then the first modification has no effect. That's one of the NetKAT axioms.

So the behavior should be exactly what you expect, once you know that ports, queries, and pipes are modeled using the same **single** conceptual field, namely `location`.

**Comment by craig-riecke** [comment]
Thank you, that explanation is helpful.  I will put that in the manual.
