### ISSUE TITLE
Replace Outdated and Redundant Wiki

### ISSUE THREAD

**Issue by craig-riecke** [frenetic-lang/frenetic#498]
Right now the wiki is a bunch of (1) outdated versions of the pages in frenetic-lang/tutorial (2) obsolete project plans for the 2014 GSOC.  IMHO they should be removed.

I'd recommend Wiki pages for the information you need closest at hand:

- A quick start (repeater app?) in every relevant language: Ocaml/Ox, Ocaml/NetKAT, Python, REST/Curl
- Command line options
- A Reference guide for each syntax: NetKAT Surface,  Python, REST

And link to the Tutorial (http://frenetic-lang.github.io/tutorials/Introduction/) and Frenetic Programmers Manual (https://github.com/frenetic-lang/manual/blob/master/programmers_guide/frenetic_programmers_guide.pdf) for in-depthness.

**Comment by jnfoster** [comment]
Definitely.

-N

**Comment by craig-riecke** [comment]
Done.
