### ISSUE TITLE
Frenetic and NetIDE

### ISSUE THREAD

**Issue by sushiljain1989** [frenetic-lang/frenetic#524]
Hi,

Is there any documentation available to make frenetic work with NetIDE ?

~Sushil

**Comment by jnfoster** [comment]
Sorry, no but we welcome contributions!

-N

**Comment by sushiljain1989** [comment]
Thanks @jnfoster for your quick reply. Could you tell me if there is any documentation about installing frenetic from scratch? I don't want to use the VM.

**Comment by jnfoster** [comment]
That's a good point. We should publish manual instructions.

For now, the shell scripts in the Vagrant repository should do the trick:

https://github.com/frenetic-lang/frenetic-vm/blob/master/root-bootstrap.sh
https://github.com/frenetic-lang/frenetic-vm/blob/master/user-bootstrap.sh

-N

**Comment by sushiljain1989** [comment]
Thanks mate, its helpful newbies like me (y)
