### ISSUE TITLE
NetKAT Program Compilation Error

### ISSUE THREAD

**Issue by sushiljain1989** [frenetic-lang/frenetic#526]
When I try to compile the Repeater program then it is not compiling successfully.
Check out the screenshot. Any workaround for this ?

![netkat - error](https://cloud.githubusercontent.com/assets/4305242/19683364/40031806-9ab2-11e6-9995-56a8176ebb00.png)

**Comment by jnfoster** [comment]
What does `ocamlfind query ulex` return?

It should look something like this:

$ ocamlfind query ulex
> /home/vagrant/.opam/4.03.0/lib/ulex


-N

**Comment by sushiljain1989** [comment]
I just did that and it returns me :
`/home/frenetic/.opam/system/lib/ulex
![ulex](https://cloud.githubusercontent.com/assets/4305242/19718943/fff50bd2-9b67-11e6-9c93-9d87ce3ad78d.png)
`

**Comment by jnfoster** [comment]
Assuming you are on the tutorial VM, does this command work?

```
ocamlbuild \
  -use-ocamlfind \
  -pkg core \
  -pkg async \
  -pkg frenetic \
  -pkg frenetic.async \
  -tag thread \
  -tag debug \
  -tag annot \
  -tag bin_annot \
  -tag short_paths \
  -cflags "-w,-40,-thread" \
  Repeater1.d.byte
```
?

I'm closing this issue as it's not really a Frenetic issue; it's an issue with the tutorials build scripts.

**Comment by sushiljain1989** [comment]
It is giving me following output :

vagrant@frenetic:~/netkat-tutorial-solutions$ ocamlbuild -use-ocamlfind -pkg core -pkg async -pkg frenetic -pkg frenetic.async -tag thread -tag debug -tag annot -tag bin_annot -tag short_paths -cflags "-w,-40,-thread" Repeater1.d.byte
+ ocamlfind ocamldep -package frenetic.async -package frenetic -package async -package core -modules Repeater1.ml > Repeater1.ml.depends
File "Repeater1.ml", line 7, characters 2-4:
Error: Syntax error
Command exited with code 2.
Compilation unsuccessful after building 1 target (0 cached) in 00:00:00.

**Comment by jnfoster** [comment]
Okay. This is going to be hard to debug piecemeal. Could you either
describe exactly which software you have installed on the VM, or else
export the image somewhere and let me play with it?

-N

**Comment by sushiljain1989** [comment]
I will upload the VM and share it with you

**Comment by sushiljain1989** [comment]
Hi @jnfoster 

You can find the VM using the following link 
https://drive.google.com/open?id=0ByIGs2BOaWbibW15SDJkY2h1V0k

~Sushil

**Comment by jnfoster** [comment]
Hi Sushil,

Okay, I looked at the VM. Our old OCaml Tutorial scripts have bit rotted. In particular, Jane Street deprecated support for camlp4 syntax extensions in their core library. The solution is to port them to PPX (as described in #507) which I'll look into with @smolkaj.

But rather than trying to get ancient software running that we are not actively supporting, you might also want to try the software environment described in the newer Frenetic Programmer's guide:

https://github.com/frenetic-lang/manual/blob/master/programmers_guide/frenetic_programmers_guide.pdf

-N

**Comment by sushiljain1989** [comment]
Hi Nate,

thanks for your reply. Actually, as a part of my master thesis, I have to work with different SDN languages & controller and NetKat is one of them. So it is kind of important for me to make it up and running.

Even for merlin, I need NetKat package. I have reported problem on its github page regarding package creation of netkat.


~Sushil

**Comment by sushiljain1989** [comment]
sorry, I forgot to ask. Could you please tell me what this "ppx" is ? Pls share any link if you have any

**Comment by jnfoster** [comment]
PPX is a new framework for building syntax extensions in OCaml. Many projects are moving away from Camlp4.

**Comment by jnfoster** [comment]
The `netkat`, `packet` `topology` `openflow` etc. packages have been deprecated and replaced with `frenetic`. 

For building Merlin, I think it would be easiest to port it to the latest version of `frenetic`. 

Alternatively, you could grab snapshots of the deprecated repositories from ca. January 2015. Everything is in GitHub.
