### ISSUE TITLE
Old issues

### ISSUE THREAD

**Issue by smolkaj** [frenetic-lang/frenetic#535]
We have 22 open issues at the moment, but I believe the large majority of them are completely outdated and do not apply to the current code base.

@jnfoster, could you take a look? I would close them myself, but these were all opened before I got involved with the frenetic code base and so I am not completely sure if it's fine to close them.

**Comment by jnfoster** [comment]
Closed a bunch.

**Comment by smolkaj** [comment]
Awesome, thanks.
