### ISSUE TITLE
common subexpression elimination on nat policy predicates

### ISSUE THREAD

**Issue by princedpw** [frenetic-lang/frenetic#59]
The nat box used by NetCoreDSL generates and prints a predicate that looks like this:

frameType = ip && dstIP = 10.0.0.254
     && frameType = ip && nwProto = tcp && tcpDstPort = 2001

where you'll notice the frameType constraint is duplicated.  Would be nice to eliminate that. 

The entire policy looks like this:

if switch = 1 && inPort = 1
  then
    (if
     frameType = ip && srcIP = 10.0.0.1
     && frameType = ip && nwProto = tcp && tcpSrcPort = 53592
       then (nwSrc 10.0.0.1->10.0.0.254; pass; tpSrc 53592->2001; pass)
       else
         if
         frameType = ip && srcIP = 10.0.0.1
         && frameType = ip && nwProto = tcp && tcpSrcPort = 53591
           then (nwSrc 10.0.0.1->10.0.0.254; pass; tpSrc 53591->2000; pass)
           else controller;
     if inPort = 1 then 2 else pass)
  else drop
|
if switch = 1 && inPort = 2
  then
    (if
     frameType = ip && dstIP = 10.0.0.254
     && frameType = ip && nwProto = tcp && tcpDstPort = 2001
       then (nwDst 10.0.0.254->10.0.0.1; pass; tpDst 2001->53592; pass)
       else
         if
         frameType = ip && dstIP = 10.0.0.254
         && frameType = ip && nwProto = tcp && tcpDstPort = 2000
           then (nwDst 10.0.0.254->10.0.0.1; pass; tpDst 2000->53591; pass)
           else controller;
     if inPort = 2 then 1 else pass)
  else drop

**Comment by arjunguha** [comment]
wow, nsfw chat here. closing this issue.

**Comment by jnfoster** [comment]
#postdocballerlyfe
