### ISSUE TITLE
jbuilder has some issuses

### ISSUE THREAD

**Issue by ZQ-XPY** [frenetic-lang/frenetic#622]
I have installed the menhir。but when i use the 'jbuilder external-lib-deps --missing @install'.it tells me that the menhir is missing
![image](https://user-images.githubusercontent.com/23526374/41704061-c6f1473e-7567-11e8-901c-4aa89b251223.png)

**Comment by jnfoster** [comment]
Can you run `menhir` from the command-line? 

If not, you might need to execute ``eval `opam config env``` to set up the `PATH` environment variable for OPAM, etc.

**Comment by jnfoster** [comment]
We've switch to Dune and confirmed that the build works.
