### ISSUE TITLE
VM file not available at any provided link 

### ISSUE THREAD

**Issue by shahzad46** [frenetic-lang/frenetic#623]
Hello everyone,
I have been trying to get the frenetic user-vm file that has all the necessary prerequisites for starting with frenetic programming. I just can't get this file anywhere. any link that I found is either expired or not correct. Help out!!

**Comment by arjunguha** [comment]
Hi @shahzad46 -- which link did you try? (And from what page/document?)

**Comment by shahzad46** [comment]
Hello @arjunguha , sorry for answering late.
[http://download.frenetic-lang.org/uservm/frenetic-uservm-current(url)
[https://s3.amazonaws.com/plasma-umass/frenetic-tutorial-vm.ova]](url)
I tried these links and search more as well but no luck.

**Comment by madiha005** [comment]
Hello everyone,
I am trying to get the frenetic user-vm file that has all the necessary prerequisites for starting with frenetic programming but the link provided on programmer guide and Wiki is not working.

http://download.frenetic-lang.org/uservm/frenetic-uservm-current

Can any one help me in knowing which link to use or how to download frenetic ?

**Comment by jnfoster** [comment]
We no longer distribute a VM. Frenetic source is available and builds with OPAM.
