### ISSUE TITLE
Error while building master branch of frenetic from Source .

### ISSUE THREAD

**Issue by madiha005** [frenetic-lang/frenetic#630]
Hi @smolkaj I tried to build the master branch of frenetic from source following the instruction in the READ ME.  I am done with 1 -4 steps successfully but when I try to build frenetic via make &&make install command as mentioned in step 5, I got following error: 
![Instructions 1](https://user-images.githubusercontent.com/48256600/54169408-fdeccf00-4448-11e9-8dfd-bc7e93a2d5ce.JPG)

Then I try

git clone -b fixes https://github.com/frenetic-lang/frenetic.git
and again, got following error
![Instructions 2](https://user-images.githubusercontent.com/48256600/54169437-1826ad00-4449-11e9-867d-ffac9a493132.JPG)

Then I tried to build it completely from the source from the following link 
https://github.com/frenetic-lang/frenetic/wiki/Source-Build
frenetic tornado 6.0.1 get successfully installed. I created topology and try to start up frenetic from below command
$ frenetic http-controller --verbosity debug

 I again ran into issue that command not found. 
![From source 1](https://user-images.githubusercontent.com/48256600/54169464-2f659a80-4449-11e9-8644-7e774e0a5040.JPG)
![From source 2](https://user-images.githubusercontent.com/48256600/54169465-2ffe3100-4449-11e9-91b9-602dea5f2115.JPG)
![From source 3](https://user-images.githubusercontent.com/48256600/54169466-2ffe3100-4449-11e9-98f1-19c297e705d9.JPG)

Can you please look into it and help me on this?
Thank You.

**Comment by jnfoster** [comment]
There is a `Makefile` in the top-level directory. It appears you didn't change into that directory (e.g., `cd frenetic`) after checking out the repository from GitHub.
