### ISSUE TITLE
ocaml-base-compiler build fail 

### ISSUE THREAD

**Issue by shahzad46** [frenetic-lang/frenetic#635]
Hello everyone.
I am trying frenetic for the first time. I was using pyretic before this.
Here is the error log when I try to create a new opam switch.
![frenetic error](https://user-images.githubusercontent.com/33058338/55777044-ac804000-5ad9-11e9-8e67-72b795e238ab.png)

**Comment by jnfoster** [comment]
This is a problem with Opam / OCaml. I'd suggest you ask in those projects and come back here when you have a working set of base packages?
