### ISSUE TITLE
IP address from frenetic

### ISSUE THREAD

**Issue by zitounh** [frenetic-lang/frenetic#645]
Hi,

First of all, I would like to thank you for your great work. I just started to investigate this tool, and it's looking  very interesting.

I want to build an application based on frenetic and mininet. I'm wondering if there is a way to get host ip addresses generated by mininet directly through frenetic (like the GET HTTP call that allows getting current switches for instance). I have seen some other application recomputing ip addresses by hand, I can think about other ways too, but I would prefer to rely on Frenetic. 

Thank you in advance,
Best,
Heytem

**Comment by jnfoster** [comment]
Unfortunately this is not built into Frenetic. However, one could write a discovery program to learn the set of IPv4 addresses of active hosts by observing and remembering who is sending traffic.
