### ISSUE TITLE
Building error

### ISSUE THREAD

**Issue by Hauser-F** [frenetic-lang/frenetic#646]
Hi,

when trying to build the project I get the following error:
![image](https://user-images.githubusercontent.com/39130087/84164970-6c1ca900-aa73-11ea-82e2-8ebc8e042a19.png)

What have I done wrong? 
Also, the links to the VMs don't work anymore. Would it be possible to provide one again?

**Comment by HaiDang9719** [comment]
I have the same issue. Any workarounds?

**Comment by jnfoster** [comment]
Let me see if I can put together a patch to get Frenetic building against a modern OCaml environment.

**Comment by jnfoster** [comment]
The build should be fixed now. 

I've only tested with the OCaml version 4.11.0 and the latest libraries from OPAM. 

I recommend running the following command,
```opam switch create 4.11.0```
and then installing dependencies as suggested in the README file.

**Comment by jnfoster** [comment]
If you checkout the latest version of the code and try 
```
opam pin frenetic .
```
it should compile successfully.
