### ISSUE TITLE
make&make install fail: unknown option '-allow-unannotated-ignores'.

### ISSUE THREAD

**Issue by davidlights** [frenetic-lang/frenetic#652]
when I follow readme.md and try to build the frenetic , I am stuck in this error.
![image](https://user-images.githubusercontent.com/34509285/190952492-be330fa5-5975-4d15-a313-9fa3d322ff55.png)

**Comment by davidlights** [comment]
![image](https://user-images.githubusercontent.com/34509285/191022301-c96c37f4-39d2-4ff2-a461-d9088847af7a.png)
there is a conflict between tcpip and ppx. when I update tcpip, it will automatically update ppx to a version that does not have '-allow-unanotated-ignores'.
Can anyone provide me a virtual machine which contains a well-built frenetic?

**Comment by jnfoster** [comment]
I just built fresh from OPAM on 4.12.1. I'm on an M1 Mac though, so some things may be non-standard.

Can you try
```
opam switch create 4.12.1 && opam install frenetic
```
and say `Y` to everything and see if that works for you?

**Comment by jnfoster** [comment]
That's great. I'll bump the version number in the `.opam` file to avoid this issue in the future.

Regarding Merlin, I haven't built it in quite a while. It has a fairly minimal dependency on Frenetic, so I don't think it'd be a huge lift, but I imagine some work would be needed to get it building and running again. Sorry.
