### ISSUE TITLE
<builtin>: recipe for target 'k_quants.o' failed

### ISSUE THREAD

**Issue by vjaideep08** [frenetic-lang/frenetic#656]
hi I am facing issue in step - LLAMA_METAL=1 make

$ LLAMA_METAL=1 make
I llama.cpp build info:
I UNAME_S:  Linux
I UNAME_P:  x86_64
I UNAME_M:  x86_64
I CFLAGS:   -I.              -O3 -std=c11   -fPIC -DNDEBUG -Wall -Wextra -Wpedantic -Wcast-qual -Wdouble-promotion -Wshadow -Wstrict-prototypes -Wpointer-arith -pthread -march=native -mtune=native -DGGML_USE_K_QUANTS -DGGML_USE_METAL -DGGML_METAL_NDEBUG
I CXXFLAGS: -I. -I./examples -O3 -std=c++11 -fPIC -DNDEBUG -Wall -Wextra -Wpedantic -Wcast-qual -Wno-unused-function -Wno-multichar -pthread -march=native -mtune=native -DGGML_USE_K_QUANTS -DGGML_USE_METAL
I LDFLAGS:   -framework Foundation -framework Metal -framework MetalKit -framework MetalPerformanceShaders
I CC:       cc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
I CXX:      g++ (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0

cc -I.              -O3 -std=c11   -fPIC -DNDEBUG -Wall -Wextra -Wpedantic -Wcast-qual -Wdouble-promotion -Wshadow -Wstrict-prototypes -Wpointer-arith -pthread -march=native -mtune=native -DGGML_USE_K_QUANTS -DGGML_USE_METAL -DGGML_METAL_NDEBUG   -c -o k_quants.o k_quants.c
k_quants.c: In function ‘ggml_vec_dot_q2_K_q8_K’:
k_quants.c:1356:36: warning: implicit declaration of function ‘_mm256_set_m128i’; did you mean ‘_mm256_set_epi8’? [-Wimplicit-function-declaration]
         const __m256i scales[2] = {_mm256_set_m128i(l_scales, l_scales), _mm256_set_m128i(h_scales, h_scales)};
                                    ^~~~~~~~~~~~~~~~
                                    _mm256_set_epi8
k_quants.c:1356:35: warning: missing braces around initializer [-Wmissing-braces]
         const __m256i scales[2] = {_mm256_set_m128i(l_scales, l_scales), _mm256_set_m128i(h_scales, h_scales)};
                                   ^
                                    {                                                                         }
k_quants.c: In function ‘ggml_vec_dot_q3_K_q8_K’:
k_quants.c:1864:35: warning: missing braces around initializer [-Wmissing-braces]
         const __m256i scales[2] = {_mm256_set_m128i(l_scales, l_scales), _mm256_set_m128i(h_scales, h_scales)};
                                   ^
                                    {                                                                         }
k_quants.c: In function ‘ggml_vec_dot_q4_K_q8_K’:
k_quants.c:2480:32: error: incompatible types when initializing type ‘__m256i {aka const __vector(4) long long int}’ using type ‘int’
         const __m256i scales = _mm256_set_m128i(sc128, sc128);
                                ^~~~~~~~~~~~~~~~
k_quants.c: In function ‘ggml_vec_dot_q5_K_q8_K’:
k_quants.c:2966:32: error: incompatible types when initializing type ‘__m256i {aka const __vector(4) long long int}’ using type ‘int’
         const __m256i scales = _mm256_set_m128i(sc128, sc128);
                                ^~~~~~~~~~~~~~~~
<builtin>: recipe for target 'k_quants.o' failed
make: *** [k_quants.o] Error 1

**Comment by jnfoster** [comment]
It seems like you might have the wrong project? `k_quants.c` is from LLaMA?!

**Comment by vjaideep08** [comment]
please help me with 

<builtin>: recipe for target 'k_quants.o' failed
make: *** [k_quants.o] Error 1

full error :
llama.cpp$ make clean && LLAMA_METAL=1 make


k_quants.c: In function ‘ggml_vec_dot_q2_K_q8_K’:
k_quants.c:1356:36: warning: implicit declaration of function ‘_mm256_set_m128i’; did you mean ‘_mm256_set_epi8’? [-Wimplicit-function-declaration]
         const __m256i scales[2] = {_mm256_set_m128i(l_scales, l_scales), _mm256_set_m128i(h_scales, h_scales)};
                                    ^~~~~~~~~~~~~~~~
                                    _mm256_set_epi8
k_quants.c:1356:35: warning: missing braces around initializer [-Wmissing-braces]
         const __m256i scales[2] = {_mm256_set_m128i(l_scales, l_scales), _mm256_set_m128i(h_scales, h_scales)};
                                   ^
                                    {                                                                         }
k_quants.c: In function ‘ggml_vec_dot_q3_K_q8_K’:
k_quants.c:1864:35: warning: missing braces around initializer [-Wmissing-braces]
         const __m256i scales[2] = {_mm256_set_m128i(l_scales, l_scales), _mm256_set_m128i(h_scales, h_scales)};
                                   ^
                                    {                                                                         }
k_quants.c: In function ‘ggml_vec_dot_q4_K_q8_K’:
k_quants.c:2480:32: error: incompatible types when initializing type ‘__m256i {aka const __vector(4) long long int}’ using type ‘int’
         const __m256i scales = _mm256_set_m128i(sc128, sc128);
                                ^~~~~~~~~~~~~~~~
k_quants.c: In function ‘ggml_vec_dot_q5_K_q8_K’:
k_quants.c:2966:32: error: incompatible types when initializing type ‘__m256i {aka const __vector(4) long long int}’ using type ‘int’
         const __m256i scales = _mm256_set_m128i(sc128, sc128);
                                ^~~~~~~~~~~~~~~~
<builtin>: recipe for target 'k_quants.o' failed
make: *** [k_quants.o] Error 1

**Comment by vjaideep08** [comment]
@jnfoster what are the steps to follow for this issue
please guide

**Comment by vjaideep08** [comment]
k_quants.c: In function ‘ggml_vec_dot_q2_K_q8_K’:
k_quants.c:1356:36: warning: implicit declaration of function ‘_mm256_set_m128i’; did you mean ‘_mm256_set_epi8’? [-Wimplicit-function-declaration]
         const __m256i scales[2] = {_mm256_set_m128i(l_scales, l_scales), _mm256_set_m128i(h_scales, h_scales)};
                                    ^~~~~~~~~~~~~~~~
                                    _mm256_set_epi8
k_quants.c:1356:35: warning: missing braces around initializer [-Wmissing-braces]
         const __m256i scales[2] = {_mm256_set_m128i(l_scales, l_scales), _mm256_set_m128i(h_scales, h_scales)};
                                   ^
                                    {                                                                         }
k_quants.c: In function ‘ggml_vec_dot_q3_K_q8_K’:
k_quants.c:1864:35: warning: missing braces around initializer [-Wmissing-braces]
         const __m256i scales[2] = {_mm256_set_m128i(l_scales, l_scales), _mm256_set_m128i(h_scales, h_scales)};
                                   ^
                                    {                                                                         }
k_quants.c: In function ‘ggml_vec_dot_q4_K_q8_K’:
k_quants.c:2480:32: error: incompatible types when initializing type ‘__m256i {aka const __vector(4) long long int}’ using type ‘int’
         const __m256i scales = _mm256_set_m128i(sc128, sc128);
                                ^~~~~~~~~~~~~~~~
k_quants.c: In function ‘ggml_vec_dot_q5_K_q8_K’:
k_quants.c:2966:32: error: incompatible types when initializing type ‘__m256i {aka const __vector(4) long long int}’ using type ‘int’
         const __m256i scales = _mm256_set_m128i(sc128, sc128);
                                ^~~~~~~~~~~~~~~~
<builtin>: recipe for target 'k_quants.o' failed
make: *** [k_quants.o] Error 1

**Comment by jnfoster** [comment]
Based on the error messages, this seems to have nothing to do with Frenetic. 

If you are trying to build / install Frenetic, can you please provide a detailed description of your environment and the specific commands you have issued? 

Or, if you are trying to build LLaMA or some other package, please ask your question on the appropriate repository.
